{% set name = "resvg" %}
{% set version = "0.46.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/RazrFalcon/resvg/archive/v{{ version }}.tar.gz
  sha256: 81a82a8de33da0fcf13fd18532d653bbd0b50b146d82c319dd0ce7294562c7c5

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses
    # # I had to disable this because it was causing a hang.
    # # <https://matrix.to/#/!SOyumkgPRWoXfQYIFH:matrix.org/$17188919988GjPNB:gitter.im?via=matrix.org&via=gitter.im&via=ifisc.uib-csic.es>
    # # For the 'strip' utility:
    # - binutils  # [win]

test:
  commands:
    - resvg --help
    - resvg --version

about:
  home: https://github.com/RazrFalcon/resvg
  license: Apache-2.0 OR MIT
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
    - THIRDPARTY.yml
  summary: An SVG rendering library.

extra:
  recipe-maintainers:
    - maresb
