{% set name = "resvg" %}
{% set version = "0.38.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/RazrFalcon/resvg/archive/v{{ version }}.tar.gz
  sha256: cdb306f62c55e06aa1071323e7dcd72e5f5d63210af108dd74549937a22bd2d2

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - cargo-bundle-licenses

test:
  commands:
    - resvg --help
    - resvg --version

about:
  home: https://github.com/RazrFalcon/resvg
  license: MPL-2.0
  license_file:
    - LICENSE.txt
    - THIRDPARTY.yml
  summary: An SVG rendering library.

extra:
  recipe-maintainers:
    - maresb
