{% set name = "resvg" %}
{% set version = "0.41.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/RazrFalcon/resvg/archive/v{{ version }}.tar.gz
  sha256: 489e767d4e87f18336ead22a99e64f338cd980a948bf875cfa60742eff7170cc

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - cargo-bundle-licenses
  run:
    # <https://conda-forge.org/news/2024/01/29/rust-175-osx-sdk/>
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  commands:
    - resvg --help
    - resvg --version

about:
  home: https://github.com/RazrFalcon/resvg
  license: MPL-2.0
  license_file:
    - LICENSE.txt
    - THIRDPARTY.yml
  summary: An SVG rendering library.

extra:
  recipe-maintainers:
    - maresb
